const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const widgetRoot = path.join(__dirname, "../config/omarchy/plugins/widgets")
const mainQml = fs.readFileSync(path.join(widgetRoot, "Main.qml"), "utf8")
const sectionQml = fs.readFileSync(path.join(widgetRoot, "WidgetSection.qml"), "utf8")
const tileQml = fs.readFileSync(path.join(widgetRoot, "WidgetTile.qml"), "utf8")

function blockBetween(source, start, end) {
  const startIndex = source.indexOf(start)
  assert.notEqual(startIndex, -1, `missing QML block: ${start}`)
  const endIndex = source.indexOf(end, startIndex)
  assert.notEqual(endIndex, -1, `missing end marker after: ${start}`)
  return source.slice(startIndex, endIndex)
}

const seekSlider = blockBetween(tileQml, "id: seekMouse", "RowLayout {")
const volumeSlider = blockBetween(tileQml, "id: volumeMouse", "Rectangle {")
const panelBackground = blockBetween(mainQml, "id: panelBackground", "Flickable {")
assert.match(seekSlider, /preventStealing:\s*true/)
assert.match(volumeSlider, /preventStealing:\s*true/)
assert.match(volumeSlider, /onPressed: function\(mouse\)/)
assert.match(volumeSlider, /onPositionChanged: function\(mouse\)/)
assert.match(volumeSlider, /onReleased: root\.dashboard\.endPlayerVolume\(\)/)
assert.match(mainQml, /readonly property bool playerMuted:/)
assert.match(mainQml, /readonly property bool playerVolumeControlEnabled:/)
assert.match(mainQml, /readonly property bool playerVolumeSliderEnabled:/)
assert.match(mainQml, /function adjustPlayerVolume\(delta\)/)
assert.match(tileQml, /id: muteBadge/)
assert.match(tileQml, /Behavior on opacity/)
assert.match(tileQml, /Behavior on scale/)
assert.ok(tileQml.includes('text: "◖))"'))
assert.match(tileQml, /enabled: root\.dashboard\.playerVolumeControlEnabled/)
assert.match(tileQml, /enabled: root\.dashboard\.playerVolumeSliderEnabled/)
assert.match(tileQml, /onClicked: root\.dashboard\.toggleMute\(\)/)

assert.match(tileQml, /onDoubleTapped:\s*root\.dashboard\.resetTileSize\(root\.tileId\)/)
assert.match(tileQml, /enabled:\s*root\.editing && !root\.dashboard\.widgetLayout\.locked/)
assert.match(tileQml, /dragTranslation\.x/)
assert.match(tileQml, /dragTranslation\.y/)
assert.match(tileQml, /onActiveTranslationChanged/)
assert.match(tileQml, /Drag\.active:\s*root\.dragInProgress/)
assert.match(tileQml, /pendingDropSectionTarget/)
assert.match(tileQml, /pendingDropTileTarget/)
assert.match(tileQml, /function containsDragPoint\(/)
assert.match(tileQml, /root\.dashboard\.draggingItems = true/)
assert.match(tileQml, /root\.dashboard\.draggingItems = false/)
assert.match(tileQml, /root\.dashboard\.moveTile\(root\.tileId/)
assert.match(tileQml, /parent:\s*root\.dragLayer/)
assert.match(tileQml, /Drag\.source:\s*root/)
assert.match(sectionQml, /keys:\s*\["omarchy-widget-tile", "omarchy-widget-section"\]/)
assert.match(sectionQml, /root\.dashboard\.moveSectionTo\(/)
assert.match(sectionQml, /dragTranslation\.x/)
assert.match(sectionQml, /onActiveTranslationChanged/)
assert.match(sectionQml, /Drag\.active:\s*root\.dragInProgress/)
assert.match(sectionQml, /pendingDropTarget = root/)
assert.match(sectionQml, /root\.dashboard\.moveSectionTo\(root\.sectionId/)
assert.match(sectionQml, /function containsDragPoint\(/)
assert.match(sectionQml, /root\.dashboard\.draggingItems = true/)
assert.match(sectionQml, /root\.dashboard\.draggingItems = false/)
assert.match(sectionQml, /parent:\s*root\.dragLayer/)
assert.match(sectionQml, /Drag\.source:\s*root/)
assert.match(sectionQml, /Drag\.supportedActions:\s*Qt\.MoveAction/)
const sectionDrop = blockBetween(sectionQml, "id: sectionDrop", "RowLayout {")
assert.match(sectionDrop, /enabled:\s*root\.editing && !root\.dashboard\.widgetLayout\.locked && !root\.dragInProgress/)
assert.match(sectionDrop, /drop\.acceptProposedAction\(\)/)
assert.match(sectionDrop, /drop\.accept\(Qt\.MoveAction\)/)
assert.match(sectionDrop, /drop\.source\.sectionId !== root\.sectionId/)
assert.match(tileQml, /Drag\.supportedActions:\s*Qt\.MoveAction/)
const tileDrop = blockBetween(tileQml, "id: tileDrop", "Behavior on scale")
assert.match(tileDrop, /enabled:\s*root\.editing && !root\.dashboard\.widgetLayout\.locked && !root\.dragInProgress/)
assert.match(tileDrop, /drop\.acceptProposedAction\(\)/)
assert.match(tileDrop, /drop\.accept\(Qt\.MoveAction\)/)
assert.match(mainQml, /interactive:\s*!root\.editing\s*\|\|\s*\(contentColumn\.implicitHeight > viewport\.height && !root\.draggingItems\)/)
assert.match(mainQml, /GridLayout\s*\{\s*Layout\.fillWidth:\s*true\s*Layout\.preferredWidth:\s*width\s*Layout\.preferredHeight:\s*64\s*columns:\s*2/s)
assert.match(mainQml, /visible:\s*viewport\.contentHeight > viewport\.height/)
assert.match(mainQml, /visible:\s*!root\.editing \|\| root\.editorTab === "layout"/)
assert.match(mainQml, /id:\s*dragOverlay/)
assert.match(mainQml, /dragLayer:\s*dragOverlay/)
assert.match(mainQml, /import QtQuick\.Effects/)
assert.match(panelBackground, /layer\.effect:\s*MultiEffect/)
assert.match(panelBackground, /maskEnabled:\s*true/)
assert.match(panelBackground, /maskSource:\s*panelCornerMask/)
assert.match(mainQml, /id:\s*panelCornerMask[\s\S]*radius:\s*24/)

console.log("widget QML interaction contract tests passed")
